services:
  postgres:
    image: postgres:17-alpine
    container_name: lock_in_pomodoro_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: lock_in
      POSTGRES_PASSWORD: lock_in
      POSTGRES_DB: lock_in_pomodoro
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
